version: '3'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"  
    networks:
      - tracing   
  servicea:
    build: .
    ports:
     - 9000:9000/tcp
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAEGER_SAMPLER_MANAGER_HOST_PORT=jaeger:5778
    networks:
      - tracing   
networks:
  tracing:
    driver: bridge
