version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.16.3
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - tracing
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
  kibana:
    image: kibana:7.16.3
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL:http://elasticsearch:9200
      - ELASTICSEARCH_HOSTS:'["http://elasticsearch:9200"]'
    depends_on:
      - elasticsearch
    networks:
      - tracing
networks:
  tracing:
    driver: bridge
